-module(swagger_power_forms).

-export([encode/1]).

-export_type([swagger_power_forms/0]).

-type swagger_power_forms() ::
    #{ 'createdBy' => binary(),
       'createdDateTime' => binary(),
       'emailBody' => binary(),
       'emailSubject' => binary(),
       'envelopes' => list(),
       'errorDetails' => swagger_error_details:swagger_error_details(),
       'instructions' => binary(),
       'isActive' => binary(),
       'lastUsed' => binary(),
       'limitUseInterval' => binary(),
       'limitUseIntervalEnabled' => binary(),
       'limitUseIntervalUnits' => binary(),
       'maxUseEnabled' => binary(),
       'name' => binary(),
       'powerFormId' => binary(),
       'powerFormUrl' => binary(),
       'recipients' => list(),
       'senderName' => binary(),
       'senderUserId' => binary(),
       'signingMode' => binary(),
       'templateId' => binary(),
       'templateName' => binary(),
       'timesUsed' => binary(),
       'uri' => binary(),
       'usesRemaining' => binary()
     }.

encode(#{ 'createdBy' := CreatedBy,
          'createdDateTime' := CreatedDateTime,
          'emailBody' := EmailBody,
          'emailSubject' := EmailSubject,
          'envelopes' := Envelopes,
          'errorDetails' := ErrorDetails,
          'instructions' := Instructions,
          'isActive' := IsActive,
          'lastUsed' := LastUsed,
          'limitUseInterval' := LimitUseInterval,
          'limitUseIntervalEnabled' := LimitUseIntervalEnabled,
          'limitUseIntervalUnits' := LimitUseIntervalUnits,
          'maxUseEnabled' := MaxUseEnabled,
          'name' := Name,
          'powerFormId' := PowerFormId,
          'powerFormUrl' := PowerFormUrl,
          'recipients' := Recipients,
          'senderName' := SenderName,
          'senderUserId' := SenderUserId,
          'signingMode' := SigningMode,
          'templateId' := TemplateId,
          'templateName' := TemplateName,
          'timesUsed' := TimesUsed,
          'uri' := Uri,
          'usesRemaining' := UsesRemaining
        }) ->
    #{ 'createdBy' => CreatedBy,
       'createdDateTime' => CreatedDateTime,
       'emailBody' => EmailBody,
       'emailSubject' => EmailSubject,
       'envelopes' => Envelopes,
       'errorDetails' => ErrorDetails,
       'instructions' => Instructions,
       'isActive' => IsActive,
       'lastUsed' => LastUsed,
       'limitUseInterval' => LimitUseInterval,
       'limitUseIntervalEnabled' => LimitUseIntervalEnabled,
       'limitUseIntervalUnits' => LimitUseIntervalUnits,
       'maxUseEnabled' => MaxUseEnabled,
       'name' => Name,
       'powerFormId' => PowerFormId,
       'powerFormUrl' => PowerFormUrl,
       'recipients' => Recipients,
       'senderName' => SenderName,
       'senderUserId' => SenderUserId,
       'signingMode' => SigningMode,
       'templateId' => TemplateId,
       'templateName' => TemplateName,
       'timesUsed' => TimesUsed,
       'uri' => Uri,
       'usesRemaining' => UsesRemaining
     }.
