-module(swagger_radio_group).

-export([encode/1]).

-export_type([swagger_radio_group/0]).

-type swagger_radio_group() ::
    #{ 'conditionalParentLabel' => binary(),
       'conditionalParentLabelMetadata' => swagger_property_metadata:swagger_property_metadata(),
       'conditionalParentValue' => binary(),
       'conditionalParentValueMetadata' => swagger_property_metadata:swagger_property_metadata(),
       'documentId' => binary(),
       'documentIdMetadata' => swagger_property_metadata:swagger_property_metadata(),
       'groupName' => binary(),
       'groupNameMetadata' => swagger_property_metadata:swagger_property_metadata(),
       'radios' => list(),
       'recipientId' => binary(),
       'recipientIdGuid' => binary(),
       'recipientIdGuidMetadata' => swagger_property_metadata:swagger_property_metadata(),
       'recipientIdMetadata' => swagger_property_metadata:swagger_property_metadata(),
       'requireAll' => binary(),
       'requireAllMetadata' => swagger_property_metadata:swagger_property_metadata(),
       'requireInitialOnSharedChange' => binary(),
       'requireInitialOnSharedChangeMetadata' => swagger_property_metadata:swagger_property_metadata(),
       'shared' => binary(),
       'sharedMetadata' => swagger_property_metadata:swagger_property_metadata(),
       'tabType' => binary(),
       'tabTypeMetadata' => swagger_property_metadata:swagger_property_metadata(),
       'templateLocked' => binary(),
       'templateLockedMetadata' => swagger_property_metadata:swagger_property_metadata(),
       'templateRequired' => binary(),
       'templateRequiredMetadata' => swagger_property_metadata:swagger_property_metadata(),
       'tooltip' => binary(),
       'tooltipMetadata' => swagger_property_metadata:swagger_property_metadata()
     }.

encode(#{ 'conditionalParentLabel' := ConditionalParentLabel,
          'conditionalParentLabelMetadata' := ConditionalParentLabelMetadata,
          'conditionalParentValue' := ConditionalParentValue,
          'conditionalParentValueMetadata' := ConditionalParentValueMetadata,
          'documentId' := DocumentId,
          'documentIdMetadata' := DocumentIdMetadata,
          'groupName' := GroupName,
          'groupNameMetadata' := GroupNameMetadata,
          'radios' := Radios,
          'recipientId' := RecipientId,
          'recipientIdGuid' := RecipientIdGuid,
          'recipientIdGuidMetadata' := RecipientIdGuidMetadata,
          'recipientIdMetadata' := RecipientIdMetadata,
          'requireAll' := RequireAll,
          'requireAllMetadata' := RequireAllMetadata,
          'requireInitialOnSharedChange' := RequireInitialOnSharedChange,
          'requireInitialOnSharedChangeMetadata' := RequireInitialOnSharedChangeMetadata,
          'shared' := Shared,
          'sharedMetadata' := SharedMetadata,
          'tabType' := TabType,
          'tabTypeMetadata' := TabTypeMetadata,
          'templateLocked' := TemplateLocked,
          'templateLockedMetadata' := TemplateLockedMetadata,
          'templateRequired' := TemplateRequired,
          'templateRequiredMetadata' := TemplateRequiredMetadata,
          'tooltip' := Tooltip,
          'tooltipMetadata' := TooltipMetadata
        }) ->
    #{ 'conditionalParentLabel' => ConditionalParentLabel,
       'conditionalParentLabelMetadata' => ConditionalParentLabelMetadata,
       'conditionalParentValue' => ConditionalParentValue,
       'conditionalParentValueMetadata' => ConditionalParentValueMetadata,
       'documentId' => DocumentId,
       'documentIdMetadata' => DocumentIdMetadata,
       'groupName' => GroupName,
       'groupNameMetadata' => GroupNameMetadata,
       'radios' => Radios,
       'recipientId' => RecipientId,
       'recipientIdGuid' => RecipientIdGuid,
       'recipientIdGuidMetadata' => RecipientIdGuidMetadata,
       'recipientIdMetadata' => RecipientIdMetadata,
       'requireAll' => RequireAll,
       'requireAllMetadata' => RequireAllMetadata,
       'requireInitialOnSharedChange' => RequireInitialOnSharedChange,
       'requireInitialOnSharedChangeMetadata' => RequireInitialOnSharedChangeMetadata,
       'shared' => Shared,
       'sharedMetadata' => SharedMetadata,
       'tabType' => TabType,
       'tabTypeMetadata' => TabTypeMetadata,
       'templateLocked' => TemplateLocked,
       'templateLockedMetadata' => TemplateLockedMetadata,
       'templateRequired' => TemplateRequired,
       'templateRequiredMetadata' => TemplateRequiredMetadata,
       'tooltip' => Tooltip,
       'tooltipMetadata' => TooltipMetadata
     }.
