-module(swagger_workspace_item).

-export([encode/1]).

-export_type([swagger_workspace_item/0]).

-type swagger_workspace_item() ::
    #{ 'callerAuthorization' => swagger_workspace_user_authorization:swagger_workspace_user_authorization(),
       'contentType' => binary(),
       'created' => binary(),
       'createdById' => binary(),
       'createdByInformation' => swagger_workspace_user:swagger_workspace_user(),
       'extension' => binary(),
       'fileSize' => binary(),
       'fileUri' => binary(),
       'id' => binary(),
       'isPublic' => binary(),
       'lastModified' => binary(),
       'lastModifiedById' => binary(),
       'lastModifiedByInformation' => swagger_workspace_user:swagger_workspace_user(),
       'name' => binary(),
       'pageCount' => binary(),
       'parentFolderId' => binary(),
       'parentFolderUri' => binary(),
       'sha256' => binary(),
       'thumbHeight' => binary(),
       'thumbnail' => swagger_page:swagger_page(),
       'thumbWidth' => binary(),
       'type' => binary(),
       'uri' => binary(),
       'userAuthorization' => swagger_workspace_user_authorization:swagger_workspace_user_authorization()
     }.

encode(#{ 'callerAuthorization' := CallerAuthorization,
          'contentType' := ContentType,
          'created' := Created,
          'createdById' := CreatedById,
          'createdByInformation' := CreatedByInformation,
          'extension' := Extension,
          'fileSize' := FileSize,
          'fileUri' := FileUri,
          'id' := Id,
          'isPublic' := IsPublic,
          'lastModified' := LastModified,
          'lastModifiedById' := LastModifiedById,
          'lastModifiedByInformation' := LastModifiedByInformation,
          'name' := Name,
          'pageCount' := PageCount,
          'parentFolderId' := ParentFolderId,
          'parentFolderUri' := ParentFolderUri,
          'sha256' := Sha256,
          'thumbHeight' := ThumbHeight,
          'thumbnail' := Thumbnail,
          'thumbWidth' := ThumbWidth,
          'type' := Type,
          'uri' := Uri,
          'userAuthorization' := UserAuthorization
        }) ->
    #{ 'callerAuthorization' => CallerAuthorization,
       'contentType' => ContentType,
       'created' => Created,
       'createdById' => CreatedById,
       'createdByInformation' => CreatedByInformation,
       'extension' => Extension,
       'fileSize' => FileSize,
       'fileUri' => FileUri,
       'id' => Id,
       'isPublic' => IsPublic,
       'lastModified' => LastModified,
       'lastModifiedById' => LastModifiedById,
       'lastModifiedByInformation' => LastModifiedByInformation,
       'name' => Name,
       'pageCount' => PageCount,
       'parentFolderId' => ParentFolderId,
       'parentFolderUri' => ParentFolderUri,
       'sha256' => Sha256,
       'thumbHeight' => ThumbHeight,
       'thumbnail' => Thumbnail,
       'thumbWidth' => ThumbWidth,
       'type' => Type,
       'uri' => Uri,
       'userAuthorization' => UserAuthorization
     }.
