-module(swagger_user_signatures).

-export([encode/1]).

-export_type([swagger_user_signatures/0]).

-type swagger_user_signatures() ::
    #{ 'adoptedDateTime' => binary(),
       'createdDateTime' => binary(),
       'customField' => binary(),
       'dateStampProperties' => swagger_date_stamp_properties:swagger_date_stamp_properties(),
       'disallowUserResizeStamp' => binary(),
       'errorDetails' => swagger_error_details:swagger_error_details(),
       'externalID' => binary(),
       'imageBase64' => binary(),
       'imageType' => binary(),
       'initials150ImageId' => binary(),
       'initialsImageUri' => binary(),
       'isDefault' => binary(),
       'lastModifiedDateTime' => binary(),
       'nrdsId' => binary(),
       'nrdsLastName' => binary(),
       'nrdsStatus' => binary(),
       'phoneticName' => binary(),
       'signature150ImageId' => binary(),
       'signatureFont' => binary(),
       'signatureId' => binary(),
       'signatureImageUri' => binary(),
       'signatureInitials' => binary(),
       'signatureName' => binary(),
       'signatureRights' => binary(),
       'signatureType' => binary(),
       'stampFormat' => binary(),
       'stampImageUri' => binary(),
       'stampSizeMM' => binary(),
       'stampType' => binary()
     }.

encode(#{ 'adoptedDateTime' := AdoptedDateTime,
          'createdDateTime' := CreatedDateTime,
          'customField' := CustomField,
          'dateStampProperties' := DateStampProperties,
          'disallowUserResizeStamp' := DisallowUserResizeStamp,
          'errorDetails' := ErrorDetails,
          'externalID' := ExternalID,
          'imageBase64' := ImageBase64,
          'imageType' := ImageType,
          'initials150ImageId' := Initials150ImageId,
          'initialsImageUri' := InitialsImageUri,
          'isDefault' := IsDefault,
          'lastModifiedDateTime' := LastModifiedDateTime,
          'nrdsId' := NrdsId,
          'nrdsLastName' := NrdsLastName,
          'nrdsStatus' := NrdsStatus,
          'phoneticName' := PhoneticName,
          'signature150ImageId' := Signature150ImageId,
          'signatureFont' := SignatureFont,
          'signatureId' := SignatureId,
          'signatureImageUri' := SignatureImageUri,
          'signatureInitials' := SignatureInitials,
          'signatureName' := SignatureName,
          'signatureRights' := SignatureRights,
          'signatureType' := SignatureType,
          'stampFormat' := StampFormat,
          'stampImageUri' := StampImageUri,
          'stampSizeMM' := StampSizeMM,
          'stampType' := StampType
        }) ->
    #{ 'adoptedDateTime' => AdoptedDateTime,
       'createdDateTime' => CreatedDateTime,
       'customField' => CustomField,
       'dateStampProperties' => DateStampProperties,
       'disallowUserResizeStamp' => DisallowUserResizeStamp,
       'errorDetails' => ErrorDetails,
       'externalID' => ExternalID,
       'imageBase64' => ImageBase64,
       'imageType' => ImageType,
       'initials150ImageId' => Initials150ImageId,
       'initialsImageUri' => InitialsImageUri,
       'isDefault' => IsDefault,
       'lastModifiedDateTime' => LastModifiedDateTime,
       'nrdsId' => NrdsId,
       'nrdsLastName' => NrdsLastName,
       'nrdsStatus' => NrdsStatus,
       'phoneticName' => PhoneticName,
       'signature150ImageId' => Signature150ImageId,
       'signatureFont' => SignatureFont,
       'signatureId' => SignatureId,
       'signatureImageUri' => SignatureImageUri,
       'signatureInitials' => SignatureInitials,
       'signatureName' => SignatureName,
       'signatureRights' => SignatureRights,
       'signatureType' => SignatureType,
       'stampFormat' => StampFormat,
       'stampImageUri' => StampImageUri,
       'stampSizeMM' => StampSizeMM,
       'stampType' => StampType
     }.
